cloudflare/privacypass-issuer

src/context/metrics.ts, src/index.ts
Add specific metrics for issuance: number of requests to the issuance endpoints (/token-request), number of signed tokens.
This allows for a better monitoring of the issuer activity.
=> Add issuance metrics

jest.config.js, package-lock.json, package.json, src/global.d.ts, src/index.ts, test/index.test.ts, test/jest.setup-file.ts
Cloudflare Workers supports native blind signature when CryptoKey algorithm is marked as [`RSA-RAW`](https://github.com/cloudflare/workerd/blob/3c85053b83a5200dffc5be5ae26cbe7577cd5ea5/src/workerd/api/crypto.c%2B%2B#L122). Using the engine for blind signature instead of relying on JavaScript libraries provides significant performance improvement.
This commit adds an optional variable `EXPERIMENTAL_RSABSSA`, which when set to `'true'` enables engine signing.
Given this is specific to Cloudflare Workers, this feature is not deemed relevant to upstream to @cloudflare/privacypass-ts or @cloudflare/blindrsa-ts, which aim to be more general. In addition, miniflare does not provide a way to test this feature, therefore the experimental flagging.
=> Add support for RSABSSA signing when built in the engine

package-lock.json, package.json, src/bindings.ts, src/context/metrics.ts, src/index.ts, src/router.ts, src/utils/hex.ts, test/index.test.ts, test/mocks.ts, wrangler.toml
To reduce the number of calls to R2, with an expensive list operation, add cache in front of issuer directory endpoint.
It's worth noting that this change does not affect token issuance. The key is still retrieve for every issuance, incurring a class A operation.
=> Add cache issuer directory

.gitignore, src/cache.ts, src/context/index.ts, src/context/metrics.ts, src/index.ts, test/index.test.ts, test/mocks.ts
To retrieve keys and sign requests, the issuer needs to retrieve keys from R2. This can be a costly operation.
This commit wraps R2 reads around two caches. An in memory cache in case the worker is hot, and a cache leveraging the cache API for a longer time.
=> Add cache on requests to R2

README.md, package-lock.json, package.json, test/e2e/index.ts, test/e2e/issuer.ts, test/e2e/tsconfig.json, test/localhost-e2e.test.ts
Allow testing an issuer end-to-end from the command line. Locally, the client fetches the issuer public key and token request uri. It then generates a token request, sends it, and validates the received token.
mTLS is supported, as it's a popular authentication method.
=> Add test:e2e target

src/context/metrics.ts, src/index.ts
Provide the requested key id, as well as a reason for failing.
=> Add metrics on issuance errors

jest.config.js, src/bindings.ts, src/context/metrics.ts, wrangler.toml
Exposes [version metadata](https://developers.cloudflare.com/workers/runtime-apis/bindings/version-metadata/) to the worker. It also adds the version ID to the default label set, allowing to track metrics across versions.
=> Add version metadata binding

src/index.ts
version on key material is an artifact of an old version of the issuer. It's not in use.
=> Remove unused code

src/errors.ts, src/router.ts
- Added a status code to the handleError call to provide more detailed error information.
- Implemented the isHTTPError function to properly type-check errors caught in the catch block.
- This ensures that HTTP errors are correctly identified and handled, improving error reporting and debugging.
=> feat: add status code and isHTTPError function

src/errors.ts
This is a noisy error. Metrics around it are sufficient. It should not be sent to sentry.
=> Ignore HeaderNotDefinedError for Sentry

src/errors.ts, src/index.ts
A bad token id is a bad request, which is HTTP 400, not HTTP 500. This informs the client it is a configuration error on their side, not a server error.
=> Fix HTTP status for bad token id

src/errors.ts
Bad token key request don't have to be sent to sentry. This creates noise. They are recorded via metrics.
Relates to the change in #51
=> Add ignore for event bad token key requests

src/index.ts
not-before should be in seconds instead of milliseconds, per the [spec](https://datatracker.ietf.org/doc/rfc9578/).
=> Fix not-before time to be in seconds

src/index.ts, test/index.test.ts
Dividing by 1000 in javascript can create a float. The spec asks for 64-bit integer.
This commit updates not-before to truncate it, ensuring it's always an integer.
In addition, it adds a regression test.
=> Fix not-before to be an integer

src/index.ts
To avoid directory cache time to match browser cache time with one predominant client, a random invalidation delay is added to the worker cache.
=> Add random delay on issuer directory expiration

src/cache.ts, src/context/index.ts, test/cache.test.ts
Add the behaviour to both InMemoryCache and APICache.
This allows to provide a reply to the client without waiting on the origin storage.
=> Add stale while revalidate behaviour cache

src/index.ts, test/index.test.ts
[RFC 9578](https://datatracker.ietf.org/doc/html/rfc9578#name-configuration) states that
`Clients SHOULD use the first key in the "token-keys" list that either does not have a "not-before" value or has a "not-before" value in the past, since the first such key is the most likely to be valid in the given time window.`
While it does not mentions the Issuer clearly, it is assumed the order in which the issuer returns the key is not random. We therefore order the keys by not-before.
This commit adds this behaviour, as well as a regression test.
=> Fix ordering of key as they SHOULD be on the preference order

src/index.ts
Move from console.log to console.debug, which is a better match for the level of granularity we are looking for
=> Fix token issuance log

src/errors.ts, src/index.ts, src/utils/keyRotation.ts, test/index.test.ts
Update clear key logic, delete keys after prevRotationDate + KEY_LIFE…SPAN (48H), except last uploaded key. This creates a 48h grace period for old keys after a key has being rotated
=> Update clear key logic 

src/index.ts
They are too verbose when integrated with [Cloudflare Logpush](https://developers.cloudflare.com/logs/reference/log-fields/account/workers_trace_events/).
We can re-enable them once that product has log level filter feature.
=> Remove console.debug lines

src/index.ts
[RFC 9578, Section 8.1](https://datatracker.ietf.org/doc/html/rfc9578#name-well-known-private-token-is) registers `/.well-known/private-token-issuer-directory` as the only well-known to serve Privacy Pass Issuer directory. This commit removes non-standard endpoint that were placed under `/.well-known` for backward compatibility of certain client implementations.
=> Remove non-standard token directory path

src/bindings.ts, src/index.ts, src/utils/keyRotation.ts, test/index.test.ts, wrangler.toml
This commit adds `KEY_NOT_BEFORE_DELAY_IN_MS` binding. This is the delay that is going to be added when generating key to their `notBefore` parameter. This allow a key to be generated at time `t` to not be valid before `t+KEY_NOT_BEFORE_DELAY_IN_MS`.
Key rotation and tests are updated accordingly.
This is backward compatible with deployed codebase, defaulting to `KEY_NOT_BEFORE_DELAY_IN_MS=0` which was the previous behaviour.
=> Add configurable not-before delay

dist/types/index.d.ts, src/index.ts
Having to receive complex types like `Response` over rpc causes a few issues with stubs and overall I believe makes for a worse API. So I propose these two methods be changed.
The `tokenDirectory` method I left untouched as that requires handling of the cache and the entire request is cached currently.
=> Make RPC request agnostic

dist/types/index.d.ts, src/cache.ts, src/context/index.ts, src/index.ts, src/types.ts, test/index.test.ts
This will require a migration to deploy. To properly implement key
clearance we need to prefix all keys. In the case where a prefix is not
present, a `_global` prefix is used. This is because we don't want
listing of the regionless keys to return keys from all regions.
Luckily the migration is "additive" and not "destructive". We just need
to duplicate the current keys in R2 but with a `_global` prefix, and as
long as the deployment is finished before a rotation everything should
just work.
=> always use a prefix when interacting with R2

package-lock.json, package.json, src/index.ts, src/utils/keyRotation.ts, test/index.test.ts
We don't have to implement cron parsing inside the worker to determine
if it needs to rotate or clear keys. We can just compare `event.cron` to
the configured cron string
=> Replace cron parsing with simpler string comparison
